# Generated by Django 4.2.5 on 2023-09-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=20)),
                ('photo', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
