# Generated by Django 4.2.5 on 2023-09-18 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_borrowbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowbook',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
