# Generated by Django 4.2.5 on 2023-09-21 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authmansoura', '0002_myaccount_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myaccount',
            name='is_admin',
            field=models.CharField(default=False, max_length=8),
        ),
    ]
